### ISSUE TITLE
Dont run

### ISSUE THREAD

**Issue by ghost** [eshon/conference#1]
root@vagrant:/home/vagrant/conference# npm install -g truffle
...
/usr/local/bin/truffle -> /usr/local/lib/node_modules/truffle/truffle.bash
/usr/local/bin/truffle-exec -> /usr/local/lib/node_modules/truffle/truffle-exec.bash
truffle@0.2.7 /usr/local/lib/node_modules/truffle
├── jsmin@1.0.1
├── colors@1.1.2
├── ether-pudding@1.0.3
├── async@1.5.0
├── cpr@0.4.3 (graceful-fs@4.1.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── finalhandler@0.4.0 (unpipe@1.0.0, escape-html@1.0.2, on-finished@2.3.0, debug@2.2.0)
├── bignumber.js@2.1.0
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── node-dir@0.1.11 (minimatch@2.0.10)
├── coffee-script@1.10.0
├── rimraf@2.4.4 (glob@5.0.15)
├── bluebird@2.10.2
├── yargs@3.30.0 (decamelize@1.1.1, camelcase@1.2.1, window-size@0.1.4, y18n@3.2.0, os-locale@1.4.0, cliui@3.1.0)
├── gaze@0.5.2 (globule@0.1.0)
├── chai@3.4.1 (assertion-error@1.0.1, type-detect@1.0.0, deep-eql@0.1.3)
├── mocha@2.3.4 (escape-string-regexp@1.0.2, supports-color@1.2.0, growl@1.8.1, commander@2.3.0, diff@1.4.0, debug@2.2.0, mkdirp@0.5.0, glob@3.2.3, jade@0.26.3)
├── uglify-js@2.6.1 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.10.0, source-map@0.5.3)
├── deasync@0.1.4 (bindings@1.2.1, nan@2.1.0)
├── lodash@3.10.1
├── solc@0.1.7-1
├── babel@5.8.34 (slash@1.0.0, path-exists@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.2, commander@2.9.0, output-file-sync@1.1.1, glob@5.0.15, chokidar@1.3.0, source-map@0.5.3, babel-core@5.8.34)
├── web3@0.14.0 (utf8@2.1.1, xmlhttprequest@1.8.0, bignumber.js@2.0.7, crypto-js@3.1.5)
└── node-sass@3.4.2 (get-stdin@4.0.1, async-foreach@0.1.3, sass-graph@2.0.1, chalk@1.1.1, glob@5.0.15, npmconf@2.1.2, nan@2.1.0, meow@3.6.0, request@2.67.0, node-gyp@3.2.0, cross-spawn@2.0.1)
root@vagrant:/home/vagrant/conference# truffle deploy

/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/loader.js:19
      for (var file of files) {
                    ^^
SyntaxError: Unexpected identifier
  at Module._compile (module.js:439:25)
  at Module._extensions..js (module.js:474:10)
  at Object.require.extensions.(anonymous function) [as .js](/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/lib/exec.es6:9:21)
  at Module._compile (module.js:456:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6](/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/lib/config.es6:12:12)
  at Module._compile (module.js:456:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6](/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/truffle.es6:14:14)
  at Module._compile (module.js:456:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6](/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

root@vagrant:/home/vagrant/conference# 

How to fix it?

**Comment by rcsousa** [comment]
Update node (the instruction bellow should get you up to 5.5 in ubuntu )

curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs
